src/utils/index.js

when split result size less than 1, the construct json string's format is wrong.

prevent JSON.parse fault when search is undefined

---

src/components/TodoList/index.scss

todolist 删除图标垂直居中

---

README.md

correct README errors

---

src/main.js

fixed: catch 'GetInfo' exception

---

src/router/index.js
src/views/excel/excel2.vue

add new export-excel function

---

src/views/excel/selectExcel.vue

fix selectExcel bug

---

src/views/theme/index.vue

:memo: typing fix

---

src/components/MDinput/index.vue
src/views/components/mixin.vue

1.可放在el-form-item标签中进行数据验证
2.增加icon属性，可使用el-icon
3.删除不需要的props属性

MDinput组件修改

---

src/vendor/Export2Excel.js
src/vendor/Export2Zip.js

Before:
After:
还有qq群是不搞了吗？我被踢了

export adaptive colwidth in excel

---

src/views/dashboard/index.vue

简化index页面组件 import 和当前 role 的判断语法

index首页代码修改

---

src/store/modules/tagsView.js
src/views/layout/components/TagsView.vue

you can see the options of closeing multiple tags by right-click

refine tagview

---

src/components/TreeTable/eval.js
src/components/TreeTable/index.vue
src/components/TreeTable/readme.md
src/lang/en.js
src/lang/zh.js
src/router/index.js
src/views/example/table/treeTable/customEval.js
src/views/example/table/treeTable/customTreeTable.vue
src/views/example/table/treeTable/treeTable.vue

增加treeTable

---

src/components/TreeTable/eval.js
src/components/TreeTable/index.vue
src/components/TreeTable/readme.md

1.删除treeTable无用的属性
2.修改readme
3.修改eval.js，给后两个参数设置默认值

修改treeTable相关

---

src/vendor/Export2Excel.js
src/views/excel/exportExcel.vue
src/views/excel/selectExcel.vue

add autoWidth variable
Breaking Changes: set `export_json_to_excel` parameter variable to Object

perf[excel]: refactor excel

---

src/styles/sidebar.scss

1. 原来的普通导航栏样式会使用 siderbar 的样式，背景黑底。
2. 修改后，sidebar 样式不变，普通导航栏可以正常使用。

siderbar 样式影响了普通导航栏样式

---

src/views/layout/components/TagsView.vue

上一个 PR 没有修改彻底
右击路由标签出现的菜单功能会有问题
作者 review 一下哈

 fix[TagView-component]: loss route querystring when operating tags

---

src/components/UploadExcel/index.vue

add file type check

---

src/views/dashboard/admin/components/TodoList/index.vue

setLocalStorgae -> setLocalStorage
单词拼写错误

Spelling mistakes setLocalStorgae -> setLocalStorage（单词拼写错误）

---

src/permission.js
src/views/login/index.vue

[Feature]:add a redirect url when not logged in 

---

src/views/table/complexTable.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1080

fix: table style bug in mini size option

---

src/components/SizeSelect/index.vue
src/views/layout/components/TagsView.vue

我看了,其他用户都是提交到master分支的.
解决的下面的这个问题.
3.8.1后新增的刷新按钮，能做到真正的刷新么? #1051

修改tags刷新按钮可能有缓存的问题

---

src/store/modules/tagsView.js
src/views/layout/components/TagsView.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1086

fix[tagsView]: when query is different update tag

---

src/views/layout/components/Sidebar/Link.vue
src/views/layout/components/Sidebar/SidebarItem.vue

Fixed https://github.com/PanJiaChen/vue-element-admin/issues/1125

fix[Sidebar]: link bug

---

src/utils/i18n.js
src/views/example/components/ArticleDetail.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1020

add: add set tagsview title demo

---

src/components/Charts/mixins/resize.js
src/views/dashboard/admin/components/LineChart.vue

fixed bug #1285

---

src/components/ThemePicker/index.vue

fix[ThemePicker]: fixed bug when oldVal is null

---

src/components/Breadcrumb/index.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1519

fix[Breadcrumb]: fixed eslint error

---

src/components/Sticky/index.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1549

perf[Sticky]: export reset method

---

src/components/Screenfull/index.vue

https://github.com/PanJiaChen/vue-element-admin/issues/1602

fix[Screenfull]: fix screenfull bug #1602

---

src/styles/sidebar.scss

https://github.com/PanJiaChen/vue-element-admin/issues/1617 , https://github.com/PanJiaChen/vue-element-admin/issues/320

perf[Navbar]: add scroll bar when the subMenu is too long

---

src/views/layout/mixin/ResizeHandler.js

https://github.com/PanJiaChen/vue-element-admin/issues/1626

perf[ResizeHandler]: optimized the judgment of isMobile

---

src/layout/components/TagsView/index.vue

To fix https://github.com/PanJiaChen/vue-element-admin/issues/1832

fix[TagsView]: fixed z-index bug

---

src/components/ErrorLog/index.vue
src/settings.js

https://github.com/PanJiaChen/vue-element-admin/issues/1830

Repair error log dialog appears incorrectly when Fixed Header is enabled

---

src/styles/sidebar.scss

https://github.com/PanJiaChen/vue-element-admin/issues/1801
https://github.com/PanJiaChen/vue-element-admin/issues/1675

fix[Sidebar]: fixed sidebar scroll bug

---

src/layout/components/Sidebar/SidebarItem.vue

To fix https://github.com/PanJiaChen/vue-element-admin/issues/1869

fix[Sidebar]: fixed external link bug

---

src/components/Charts/keyboard.vue
src/components/DragSelect/index.vue
src/filters/index.js
src/layout/components/index.js
src/layout/index.vue
src/utils/index.js
src/utils/openWindow.js
src/utils/scrollTo.js
src/utils/validate.js
src/views/components-demo/sticky.vue
src/views/tab/index.vue

Add jsdoc for utils

---

src/views/example/components/ArticleDetail.vue

fix：修复display_time总为空

---

src/views/redirect/index.vue

To fix https://github.com/PanJiaChen/vue-element-admin/issues/2032

fix[redirect]: fix redirect bug in vue-devtools

---

README.es.md
README.ja.md
README.md
README.zh-CN.md

This pull request add support to readme for Spanish language, note que all credits is keeped.
Pleas add it to master.
Best regards

docs: add support to readme for Spanish

---

README.es.md

Hi everybody, this pull request have a minor change for ES translation.
Best regars

Add some translation, minor change

---

src/views/login/index.vue

To fixed https://github.com/PanJiaChen/vue-element-admin/issues/2011

perf[Login]: support other query

---

src/views/dashboard/admin/components/BarChart.vue
src/views/dashboard/admin/components/LineChart.vue
src/views/dashboard/admin/components/PieChart.vue
src/views/dashboard/admin/components/RaddarChart.vue
src/views/dashboard/admin/components/mixins/resize.js

To fixed https://github.com/PanJiaChen/vue-element-admin/issues/2116

fix[Chart]: fixed chart bug in keep-alive

---

package.json

…module 'autoprefixer'" and fix this error .

chore: add autoprefixer to devDependencies

---

README.zh-CN.md

修正README.zh-CN.md上的错别字

---

package.json

FIx  cannot find module '.../node_modules/eslint/lib/api.js/package.json' bug,see https://github.com/vuejs/vue-cli/issues/4231.

update @vue/cli-plugin-eslint version

---

src/views/table/complex-table.vue

Fix: Form header sort icon is out of sync

---

src/utils/index.js

修改parseTime函数：返回类型为string|null，正则匹配，结果位数不足补零的方式。

perf[utils.js]: perf parseTime function

---

src/store/modules/tagsView.js

优化：顶部标签栏缓存数组删除元素的函数

---

src/layout/components/TagsView/index.vue

To fix https://github.com/PanJiaChen/vue-element-admin/issues/2648

fix[TagsView]: fixed click.middle can close affixed tag bug

---

src/views/table/inline-edit-table.vue

perf: format inline edit table

---

src/views/table/drag-table.vue

perf: format drag table

---

src/views/table/complex-table.vue

perf: complex table

---

plop-templates/store/index.hbs
plop-templates/store/prompt.js
plopfile.js

new generate store

---

src/views/icons/index.vue

fix[icons]:fixed eslint 1 error and 2 warnings

---

src/components/Charts/mixins/resize.js

To fixed https://github.com/PanJiaChen/vue-element-admin/issues/2913

fix[Charts]: fix charts resize in keep-alive bug

---

src/views/profile/components/UserCard.vue

fix[profile/UserCard]: fixed wrong key name

---

src/views/tab/index.vue

format: component names should be PascalCase

perf: format component names as PascalCase

---

src/components/SvgIcon/index.vue

fix: svg support old broswer

---

vue.config.js

fix: use vue-cli default source-map

---

src/components/Tinymce/index.vue

File path: src/components/Tinymce/index.vue
```javascript
//it will try to keep these URLs intact
//https://www.tiny.cloud/docs-3x/reference/configuration/Configuration3x@convert_urls/
//https://stackoverflow.com/questions/5196205/disable-tinymce-absolute-to-relative-url-conversions
convert_urls: false
```

perf[Tinymce]: editor try to keep these URLs intact

---

src/main.js

Should be use english for all developer

perf: change default element-ui language to english

---

src/layout/components/TagsView/ScrollPane.vue
src/layout/components/TagsView/index.vue

修改如下：
当拖动tagsview 滚动条时，关闭右键菜单。

perf: when tags-view scroll close the right-menu

---

src/utils/index.js
tests/unit/utils/parseTime.spec.js

fix[parseTime]: fixed when pass null

---

src/directive/permission/permission.js

To fixed https://github.com/PanJiaChen/vue-element-admin/issues/3240

fix[v-permission]: support dynamic set roles

---

vue.config.js

add runtime.js to fileBlacklist

fix[chore]: do not preload runtime.js

---

src/utils/permission.js

return some  function return value, the code logic is simplified

perf[permission.js]: remove useless code
