package.json
解决windows10 64bit 下 sass 编译报错，和跨平台下的执行 npm run build:xxx 错误
=> 更新node-sass和增加跨平台执行npm run build的环境变量问题

src/permission.js
发现两种情况会导致NProgress无法正确结束：
1、已登录时手动修改hash至login
2、动态修改权限后，进入没有权限的页面，点击浏览器的后退
=> fix: fix undone NProgress in hash mode

src/components/ThemePicker/index.vue, src/utils/index.js
1. 当使用`"element-ui": "^2.0.7"`时，原[getVersion](https://github.com/PanJiaChen/vue-element-admin/compare/master...lvsmart:master#diff-8968c62593320351ced6a0ef776ef599L270)方法返回`^2.0.7`，导致获取`index.css`出错
2. 原注释：`verison`拼写错误
3. 从node_modules直接获取element-ui版本号，更加直接，准确。
=> get real version from node_modules

index.html
Originally the script tag was in the body tag, but moved to the outside by f2fcdee.
=> fix: misplaced script tag

package.json
The vue-loader build error caused by Prettier have been fixed
https://twitter.com/vuejs/status/1001098280326107138
=> Upgrade vue-loader

src/components/Tinymce/index.vue
When get rich editor value(null) from backend,it will occur error
```
Error in nextTick: "TypeError: Cannot read property 'replace' of null"
```
So I set val to '' to avoid it
=> fix(Tinymce): When content is null,set content to '' to avoid error

src/store/modules/tagsView.js, src/views/layout/components/TagsView.vue
TagView 组件补全
在 `$store.state.tagsView.visitedViews` 中保存完整的 route 对象
使用场景：可以将 query 在 TagView 组件中保存，通过 Tag 切换路由不丢失 querystring 等
=> Support route querystring in layout TagView

build/webpack.base.conf.js, src/main.js
Detail see [Runtime-Compiler-vs-Runtime-only](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only)
=> chore: use Runtime-only

src/store/modules/tagsView.js
state.cachedViews -> i type is string slice(begin: number, end: number)
=> state.cachedViews.slice error

package.json, src/views/example/components/ArticleDetail.vue
It seems that there is no need of 'vue-multiselect'.
So just simply remove the 'vue-multiselect' dependency.
=> chore: remove vue-multiselect

src/store/modules/permission.js, src/store/modules/user.js
后台菜单->权限测试页->指令权限 切换角色 会正确 刷新侧边栏
> /src/store/modules/permission.js
原方法在递归筛选侧边菜单后， 会意外修改原始 asyncRouterMap 导致侧边菜单重绘不正常
已经用新方法替代修复  结果入下图
=> switch roles will refresh the sidebar correctly

src/mock/index.js
修复 Mock 导致 Cookie 丢失的问题，只有在 XHR.open() 周期时，自定义的 withCredentials 会被挂载，此时检查是否是未被拦截的 xhr，并挂载自定义的 withCredentials ，无则默认为 false
=> 修复 Mock 导致请求丢失 Cookie 的问题

src/components/ScrollPane/index.vue, src/views/layout/components/TagsView.vue
1.fix[tagsView]:fixed visited view move to currentTag
2.edit the scroll regular friendly
=> 修改了TagView滚动条的bug和滚动的规则。

src/views/example/components/ArticleDetail.vue
Why need to make a copy of this.$route here?
Because if you enter this page and quickly switch tag, may be in the execution of the setTagsViewTitle function, this.$route is no longer pointing to the current page
=> fix[TagsView]: fixed tags title bug

src/views/example/components/ArticleDetail.vue
创建文章里js里有验证规则，但是由于少了<el-form-item>元素而不起作用。
=> Add <el-form-item> wrapper for validate

src/components/ScrollPane/index.vue
ScrollPane无用代码和冗余代码 --------moveToTarget这个方法中，我认为cuurentTag为第一个和最后一个时，不用去遍历节点找preTag和nextTag，此外，visitedViews[i].length > 1，我认为是没有意义的，我不理解为什么要这样用，为什么要去判断当前节点的length，是undifined啊，所以删除了里面的for循环
=> 修改currentTag为中间tag时查询前后tag的方式

src/styles/sidebar.scss, src/styles/variables.scss
Sometime we want to adjust sidebar width and it is helpful to have this config in variables.scss
=> Add sidebar width to variables.scss

src/components/DndList/index.vue
https://github.com/PanJiaChen/vue-element-admin/issues/1524
=> fix[DndList]: fixed drag bug #1524

src/utils/index.js
修复传入的时间戳是字符串类型，不能转换时间的问题
例：parseTime("1548221490638")
=> 优化 parseTime

src/components/UploadExcel/index.vue
https://github.com/PanJiaChen/vue-element-admin/issues/1520
=> perf[UploadExcel]: optimize code

src/views/layout/components/TagsView.vue
refresh 时会使用fullpath进行路由跳转，但是initTags没有对fullpath赋值，导致refresh dashboard 失败
=> #1649 404 when refresh dashboard

src/views/table/dragTable.vue
To Fix https://github.com/PanJiaChen/vue-element-admin/issues/1664
=> fix[DragTable]: support multiple drag-table

src/directive/waves/waves.js
BUG issue #1704 所示，现提出解决方案，若没问题的话请求合并 谢谢
=> waves bug fixed, Fix issue #1704: v-waves bug fixed

src/utils/index.js
Issue attempted to fix: https://github.com/PanJiaChen/vue-element-admin/issues/1711
=> fix[utils]: fixed param2Obj not decoding plus sign (#1711)

src/directive/el-table/adaptive.js, src/directive/el-table/index.js
demo ：http://jsrun.net/a3XKp/edit
=> 增加 el-table 自适应高度指令

src/vendor/Export2Excel.js, src/views/excel/exportExcel.vue
业务中有个复杂导出的需求，在vue-element-admin的基础上实现了导出。样式的问题，可能还需要修复
=> feature 增加复杂表头导出示例

src/views/example/components/ArticleDetail.vue
其实这个属性还是看作者写菜单模糊搜索下拉框时候发现的，觉得体验非常棒。虽然文章模块这里只是一个示例，但是我觉得还是加上比较好。
=> （创建文章页面）模糊搜索下拉框，在输入框按下回车，选择第一个匹配项

src/components/DndList/index.vue, src/components/Kanban/index.vue, src/views/table/dragTable.vue
To fix https://github.com/PanJiaChen/vue-element-admin/issues/1839
=> fix[Drag]: fixed drag bug in firefox

src/router/index.js
权限测试页面中，面包屑导航如“首页/页面权限”展示为“首页/权限测试页/页面权限”，Zip页面对应面包屑导航亦同。
=> revise the breadcrumb navigation of permission and zip

README.ja.md, src/components/LangSelect/index.vue, src/components/Tinymce/index.vue, src/lang/index.js, src/lang/ja.js, src/views/i18n-demo/index.vue, src/views/i18n-demo/local.js
这个项目非常好，希望可以增加日本的粉丝。
但准备提交pr时，才发现原来要移除 i18n https://github.com/PanJiaChen/vue-element-admin/pull/1828 😭。
还是希望可以保留多语言支持。
=> Add ja Lang, please don't remove i18n 

src/components/SvgIcon/index.vue
Support import `svg` via external links,
such as:
`<svg-icon icon-class="https://xxxx.svg />`
=> feat[SvgIcon]: support import svg from url

src/store/index.js
Hi guy, thanks for it great app.
I need load custom store with a sub-module like is showed on image:
This change allows add a sub-folder to store/modules and add all stores of sub-folder to global store
Please take a time for review it, I use this source code just now and worked
Best Regard
=> perf[store]: add support to sub-modules

jsconfig.json
import getPageTitle from '@/utils/get-page-title'
配置此“配置文件”，vscode中可实现对上述引用文件方式，Ctrl+鼠标左键的跳转。
=> 添加“vscode对alias全局变量的跳转”配置文件

src/store/modules/user.js
To fixed https://github.com/PanJiaChen/vue-element-admin/issues/2485
=> fix[logout]: empty tagsview when logout

src/layout/components/TagsView/index.vue
To fixed https://github.com/PanJiaChen/vue-element-admin/issues/2171
=> fix[TagsView]: fixed toLastView bug

src/components/SvgIcon/index.vue
https://cloud.tencent.com/developer/section/1424047
=> SVG 2删除了对xlink命名空间的需要，所以不xlink:href应该使用href。

src/layout/components/Navbar.vue
原先只能点击文字退出，点击下拉框文字旁边会关闭下拉框并没有执行退出动作
=> fix[Logout]: click blank area of ​​dropDown able to logout

src/layout/components/Sidebar/SidebarItem.vue
The class `menu-wrapper` isn't defined anywhere in the codebase and I think it is appropriate to remove it.
=> perf[Menu]: remove unused menu-wrapper

src/views/login/index.vue
=> perf: optimize checkCapslock method

src/router/index.js
稍微解释一下，vue-router 添加子路由的时候可以添加 path 为空的路由，例如
```
{
path: '/user',
children: [
{ path: '', name: 'UserList' },
{ path: ':id', name: 'UserDetail' }
]
}
```
当路由跳转到 UserList 时候，页面路径为 /user/
而跳转到 UserDetail 时候，页面路径为 /user/35
二者的区别在于最后少了一个 /
目前的 redirect 页面这种正则匹配会导致，对于 UserList 这种路由，刷新的时候会重定向到 /user，少了一个 / 
因此我稍微修改了一下，可以修复这个问题
=> fix: fixed redirect path regex

mock/index.js, mock/mock-server.js
我觉得原来的功能就挺好的，mock的数据始终是用来做前端开发的。
用代理的方式，把dev-api改写到mock仿真的数据思路就很好。
其中登录405，其实都是POST请求，代理转换出现问题，就是
http-proxy-middleware的锅，我已经解决。
如果楼主同意，我可以在原来的基础上修改代码并pull request。
并提供便捷的配置方式。
主要思路（目前我自己的代码已经实现）
1. 在.env.development文件中增加环境变量配置项，用来切换mock和mock-server
（为什么在这里面配置，因为这里面配置项前端后端都可用）
2. 根据.env.development中的相关配置项，在vue.config.js的devServer.before中启动
mock-server并
3. 在main.js中根据.env.development的相关配置项，启动浏览器拦截的mock
=> perf[Mock]: set responseFake to mock-server.js

src/utils/index.js, tests/unit/utils/parseTime.spec.js
"2020-03-20"  这种时间格式在谷歌浏览器和高版本的火狐浏览器中是没有问题的，但是在ie浏览器和safari浏览器中会提示Invalid Date。这个问题直接导致ie与safari浏览器中不能正常处理时间问题。
在转换前换成"2020/03/20" 这样的格式。
=> fix:fixed parseTime bug in ie and safari

README.es.md, README.ja.md, README.md, README.zh-CN.md, sandbox.config.json
This PR provides the option to import the project into CodeSandbox so that folks can try out vue-element-admin without any local setup.
The config file is required to tell CodeSandbox to use the Node container template on import rather than the Vue-CLI one it defaults to. No other code changes are required - the vue-element-admin repo is imported when the button is clicked so there's no on-going maintenance required or external code to keep up to date etc.
Until this is merged the import button link won't work - you can use https://codesandbox.io/s/github/garethx/vue-element-admin to try it out.
=> feat: add option to try project on CodeSandbox

src/styles/element-ui.scss
当四个汉字时，`size="mini" ` 左右padding不一致
=> fix[css]: min btn width

mock/article.js, mock/index.js, mock/mock-server.js, mock/remote-search.js, mock/role/index.js, mock/role/routes.js, mock/user.js, mock/utils.js, package.json
1. change `mock file` es-module to common-js 
2. remove @babel/register
reason: Mock serve will not be compiled by Babel, so if you use `import`, you need to import `babel/register`, but it is not meaningful, and the compilation speed will be slower. So change all files to commonjs
=> refactor: change mock files to commonjs

src/utils/index.js, tests/unit/utils/param2Obj.spec.js
重写 param2Obj 避免 get 入参值存在 ‘=’ ,微信分享链接url可能自带含有 ‘=’ ‘==’的入参，导致原 param2Obj 解析出现问题
=> fix[utils]: param2Obj bug when url params includes ==

vue.config.js
preserveWhitespace Deprecated since vue@2.6
Recommend `whitespace: 'condense'`, it is the default config in new vue-cli https://github.com/vuejs/vue-cli/pull/3853
Detail: https://github.com/vuejs/vue/issues/9208#issuecomment-450012518
=> perf[chore]: remove preserveWhitespace config

src/components/Tinymce/index.vue
perf[Tinymce]: remove useless code
=> perf[Tinymce]: remove useless code
